
import React from 'react';
import { 
  Github, 
  Linkedin, 
  Facebook, 
  Twitter, 
  Instagram, 
  Youtube, 
  Music2, 
  Settings,
  Code2,
  Smartphone,
  Palette,
  Zap,
  Globe,
  Mail,
  Phone,
  MapPin,
  Briefcase,
  User,
  Star,
  CheckCircle2,
  ArrowUpRight,
  Loader2,
  Plus,
  Trash2,
  Edit2,
  Save,
  X,
  BookOpen,
  Calendar,
  Layers,
  Code,
  Layout,
  Cpu,
  Database,
  Cloud,
  Terminal,
  Shield,
  Search,
  MessageSquare,
  Send,
  Quote,
  ArrowLeft,
  ArrowRight,
  Sun,
  Moon,
  Languages,
  Check,
  Home
} from 'lucide-react';

export const getIconByName = (name: string, size = 20, className = "") => {
  const icons: Record<string, any> = {
    github: Github,
    linkedin: Linkedin,
    facebook: Facebook,
    twitter: Twitter,
    instagram: Instagram,
    youtube: Youtube,
    tiktok: Music2,
    settings: Settings,
    code2: Code2,
    smartphone: Smartphone,
    palette: Palette,
    zap: Zap,
    globe: Globe,
    mail: Mail,
    phone: Phone,
    mappin: MapPin,
    briefcase: Briefcase,
    user: User,
    star: Star,
    checkcircle2: CheckCircle2,
    arrowupright: ArrowUpRight,
    loader2: Loader2,
    plus: Plus,
    trash2: Trash2,
    edit2: Edit2,
    save: Save,
    x: X,
    bookopen: BookOpen,
    calendar: Calendar,
    layers: Layers,
    code: Code,
    layout: Layout,
    cpu: Cpu,
    database: Database,
    cloud: Cloud,
    terminal: Terminal,
    shield: Shield,
    search: Search,
    messagesquare: MessageSquare,
    send: Send,
    quote: Quote,
    arrowleft: ArrowLeft,
    arrowright: ArrowRight,
    sun: Sun,
    moon: Moon,
    languages: Languages,
    check: Check,
    home: Home
  };

  const IconComponent = icons[name.toLowerCase().replace(/\s+/g, '')] || Globe;
  return <IconComponent size={size} className={className} />;
};

export const ICON_NAMES = [
  'github', 'linkedin', 'facebook', 'twitter', 'instagram', 'youtube', 'tiktok', 'settings',
  'code2', 'smartphone', 'palette', 'zap', 'globe', 'mail', 'phone', 'mappin', 'briefcase',
  'user', 'star', 'checkcircle2', 'arrowupright', 'loader2', 'plus', 'trash2', 'edit2',
  'save', 'x', 'bookopen', 'calendar', 'layers', 'code', 'layout', 'cpu', 'database',
  'cloud', 'terminal', 'shield', 'search', 'messagesquare', 'send', 'quote', 'arrowleft',
  'arrowright', 'sun', 'moon', 'languages', 'check', 'home'
];
